name: epigenetic-oscillator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - ipywidgets>=7.6.0
  - notebook>=6.4.0
  - pip
  - pip:
    - ipywidgets 