name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update environment.yml
      run: |
        pip install conda-env-export
        python -c "import conda_env_export; conda_env_export.export('environment.yml', explicit=False)"
        
    - name: Commit changes if necessary
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add environment.yml
        git diff --quiet && git diff --staged --quiet || git commit -m "Update environment.yml"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 